<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Add</strong> profile calendar' => '',
    'Allow participation state \'decline\'' => '',
    'Allow participation state \'maybe\'' => '',
    'Attending' => '',
    'Close' => '',
    'Edit' => '',
    'Enable' => '',
    'Event Type' => '',
    'Event type color' => '',
    'In order to add events to your profile, you have to enable the calendar module first.' => '',
    'Interested' => '',
    'Invalid event type id selected.' => '',
    'Invited' => '',
    'Maximum number of participants' => '',
    'Next' => '',
    'Public' => '',
    'Send update notification' => '',
    'Time Zone' => '',
    'canceled' => '',
    'Adds an calendar for private or public events to your profile and mainmenu.' => 'Tambahkan kalender untuk privat atau acara publik ke profil dan main menu',
    'Adds an event calendar to this space.' => 'Tambahkan kalender acara ke ruang ini',
    'All Day' => 'Setiap Hari',
    'Attending users' => 'Pengguna menghadiri',
    'Calendar' => 'kalender',
    'Declining users' => 'Pengguna menurun',
    'Description' => 'Deskrippsi',
    'End Date' => 'Tanggal berakhir',
    'End Time' => 'Waktu berakhir',
    'End time must be after start time!' => 'waktu akhir harus setelah waktu mulai !!',
    'Event' => 'Acara',
    'Event not found!' => 'Acara tidak ditemukan',
    'ID' => 'ID',
    'Maybe attending users' => 'Mungkin bisa menghadiri',
    'Participation Mode' => 'Mode Partisipasi',
    'Start Date' => 'Tanggal dimulai',
    'Start Time' => 'Waktu dimulai',
    'Title' => 'Judul',
    'You don\'t have permission to delete this event!' => 'kamu tidak mempunyai akses untuk menghapus acara ini!',
];
