<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> event' => 'buat acara',
    '<strong>Edit</strong> event' => 'Ubah acara',
    '<strong>Note:</strong> This event will be created on your profile. To create a space event open the calendar on the desired space.' => 'Catatan: acara ini akan dibuat di profil kamu. Untuk membuat acara di ruang kamu bisa membuka kalender di ruang kamu',
    'Delete' => 'Hapus',
    'Description' => 'Deskripsi',
    'End Date/Time' => 'Tanggal/Waktu berakhir',
    'Everybody can participate' => 'Semua orang dapat berpartisipasi',
    'No participants' => 'Tidak berpartisipasi',
    'Title' => 'Judul',
];
