<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Choose</strong> target calendar' => '',
    'Birthday' => '',
    'Cancel Event' => '',
    'Download as ICS file' => '',
    'Profile Calendar' => '',
    'Reopen Event' => '',
    '{displayName} Birthday' => '',
    '<strong>Add</strong> profile calendar' => '<strong>Dodaj</strong> profilni kalendar',
    'Adds a calendar for private or public events to your profile and main menu.' => 'Dodavaje kalendar za privatne ili javne događaje na vaš profil i glavni izbornik.',
    'Adds an event calendar to this space.' => 'Dodaje kalendar događaja u ovaj prostor.',
    'All Day' => 'Cijeli dan',
    'Allow participation state \'decline\'' => 'Dopusti status sudjelovanja "odbij"',
    'Allow participation state \'maybe\'' => 'Dopusti status sudjelovanja "možda"',
    'Attending' => 'Prisustvovati',
    'Attending users' => 'Polaznici',
    'Calendar' => 'Kalendar',
    'Close' => 'Zatvori',
    'Declining users' => 'Odbijanje korisnika',
    'Description' => 'Opis',
    'Edit' => 'Uredi',
    'Enable' => 'Omogući',
    'End Date' => 'Datum završetka',
    'End Time' => 'Vrijeme završetka',
    'End time must be after start time!' => 'Vrijeme završetka mora biti nakon vremena početka!',
    'Event' => 'Događaj',
    'Event Type' => 'Tip događaja',
    'Event not found!' => 'Događaj nije pronađen!',
    'Event type color' => 'Boja vrste događaja',
    'ID' => 'ID',
    'In order to add events to your profile, you have to enable the calendar module first.' => 'Da biste dodali događaje u svoj profil, najprije morate omogućiti kalendarski modul.',
    'Interested' => 'Zainteresiran',
    'Invalid event type id selected.' => 'Odabran je ID vrste vrste događaja koji nije valjan.',
    'Maximum number of participants' => 'Maksimalan broj sudionika',
    'Maybe attending users' => 'Mogući sudionici',
    'Next' => 'Dalje',
    'Participation Mode' => 'Način sudjelovanja',
    'Public' => 'Javno',
    'Send update notification' => 'Pošalji obavijest o ažuriranju',
    'Start Date' => 'Datum početka',
    'Start Time' => 'Vrijeme početka',
    'Time Zone' => 'Vremenska zona',
    'Title' => 'Naziv',
    'You don\'t have permission to delete this event!' => 'Nemate dopuštenje da obrišete ovaj događaj!',
    'canceled' => 'otkazano',
];
