<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(disabled)' => '',
    'Here you can manage calendar types provided by other modules.' => '',
    'Other Calendars Configuration' => '',
    '(global)' => '(globalno)',
    '<strong>Calendar</strong> module configuration' => '<strong>Kalendar</strong> postavke modula',
    '<strong>Confirm</strong> Deletion' => '<strong>Potvrdi</strong> brisanje',
    'Adds an snippet with upcoming events to your users dashboard.' => 'Dodaje se isječak s nadolazećim događajima na upravljačku ploču.',
    'Create new type' => 'Kreiraj novi tip',
    'Default event settings' => 'Zadane postavke događaja',
    'Delete' => 'Obriši',
    'Do you really want to delte this event type?' => 'Želite li zaista ukloniti ovu vrstu događaja?',
    'Event Type Configuration' => 'Konfiguracija vrste događaja',
    'Half a year' => 'Pola godine',
    'Here you can configure default settings for new calendar events.' => 'Ovdje možete konfigurirati zadane postavke za nove kalendarske događaje.',
    'Here you can configure default settings for new calendar events. These settings can be overwritten on space/profile level.' => 'Ovdje možete konfigurirati zadane postavke za nove kalendarske događaje. Ove postavke mogu se promijeniti na razini prostora / profila.',
    'Here you can manage your event types.' => 'Ovdje možete upravljati vrstama događaja.',
    'If activated, the calendar top menu item and dashboard snippet is only visible for users having the calendar module installed in their profile.' => 'Ako je aktiviran, stavka izbornika kalendara i isječak upravljačke ploče vidljivi su samo korisnicima koji imaju kalendarski modul instaliran u svom profilu.',
    'Interval of upcoming events' => 'Interval nadolazećih događaja',
    'Max event items' => 'Maksimalne stavke događaja',
    'Name' => 'Ime',
    'One month' => 'Jedan mjesec',
    'One week' => 'Jedan tjedan',
    'One year' => 'Jedna godina',
    'Only show top menu item and snippet if the module is installed in the users profile' => 'Prikaži samo gornju stavku izbornika i isječak ako je modul instaliran u korisničkom profilu',
    'Reset' => 'Reset',
    'Show snippet' => 'Prikaži isječak',
    'Sort order' => 'Poredaj redoslijed',
    'There are currently no event types available.' => 'Trenutačno nema dostupnih vrsta događaja.',
    'Upcoming events snippet' => 'Isječak nadolazećih događaja',
];
