<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Choose</strong> target calendar' => '',
    'Birthday' => '',
    'Cancel Event' => '',
    'Download as ICS file' => '',
    'Profile Calendar' => '',
    'Reopen Event' => '',
    '{displayName} Birthday' => '',
    '<strong>Add</strong> profile calendar' => '<strong>Aggiungi</strong> il calendario del profilo',
    'Adds a calendar for private or public events to your profile and main menu.' => 'Aggiunge un calendario per eventi privati e pubblici sul tuo profilo e sul tuo menù principale',
    'Adds an event calendar to this space.' => 'Aggiunge un evento al calendario per questo space.',
    'All Day' => 'Tutto il giorno',
    'Allow participation state \'decline\'' => 'Permetti a partecipanti di selezionare \'non parteciperò\'',
    'Allow participation state \'maybe\'' => 'Permetti a partecipanti di selezionare \'forse\'',
    'Attending' => 'Parteciperò',
    'Attending users' => 'Utenti che partecipano',
    'Calendar' => 'Calendario',
    'Close' => 'Chiudi',
    'Declining users' => 'Utenti che hanno rifiutato',
    'Description' => 'Descrizione',
    'Edit' => 'Modifica',
    'Enable' => 'Abilita',
    'End Date' => 'Data fine',
    'End Time' => 'Ora fine',
    'End time must be after start time!' => 'La data fine deve essere successiva alla data inizio!',
    'Event' => 'Evento',
    'Event Type' => 'Tipologia di Evento',
    'Event not found!' => 'Evento non trovato!',
    'Event type color' => 'Colore degli Eventi',
    'ID' => 'ID',
    'In order to add events to your profile, you have to enable the calendar module first.' => 'Per poter aggiungere degli eventi nel tuo profilo, devi aver prima abilitato il Modulo Calendario.',
    'Interested' => 'Interessante',
    'Invalid event type id selected.' => 'Tipologia di Evento non corretta',
    'Maximum number of participants' => 'Numero Massimo di Partecipanti',
    'Maybe attending users' => 'Utenti che forse parteciperanno',
    'Next' => 'Successivo',
    'Participation Mode' => 'Modalità di partecipazione',
    'Public' => 'Pubblico',
    'Send update notification' => 'Invia notifica di aggiornamento',
    'Start Date' => 'Data inizio',
    'Start Time' => 'Ora inizio',
    'Time Zone' => 'Fuso Orario',
    'Title' => 'Titolo',
    'You don\'t have permission to delete this event!' => 'Non hai il permesso di cancellare questo evento!',
    'canceled' => 'cancellato',
];
