<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Add</strong> profile calendar' => '',
    'Allow participation state \'decline\'' => '',
    'Allow participation state \'maybe\'' => '',
    'Attending' => '',
    'Close' => '',
    'Edit' => '',
    'Enable' => '',
    'Event Type' => '',
    'Event type color' => '',
    'In order to add events to your profile, you have to enable the calendar module first.' => '',
    'Interested' => '',
    'Invalid event type id selected.' => '',
    'Invited' => '',
    'Maximum number of participants' => '',
    'Next' => '',
    'Public' => '',
    'Send update notification' => '',
    'Time Zone' => '',
    'canceled' => '',
    'Adds an calendar for private or public events to your profile and mainmenu.' => 'Aggiunge un calendario per eventi privati e pubblici sul tuo profilo e sul tuo menù principale',
    'Adds an event calendar to this space.' => 'Aggiunge un evento al calendario per questo space.',
    'All Day' => 'Tutto il giorno',
    'Attending users' => 'Utenti che partecipano',
    'Calendar' => 'Calendario',
    'Declining users' => 'Utenti che hanno rifiutato',
    'Description' => 'Descrizione',
    'End Date' => 'Data fine',
    'End Time' => 'Ora fine',
    'End time must be after start time!' => 'La data fine deve essere successiva alla data inizio!',
    'Event' => 'Evento',
    'Event not found!' => 'Evento non trovato!',
    'ID' => 'ID',
    'Maybe attending users' => 'Utenti che forse parteciperanno',
    'Participation Mode' => 'Modalità di partecipazione',
    'Start Date' => 'Data inizio',
    'Start Time' => 'Ora inizio',
    'Title' => 'Titolo',
    'You don\'t have permission to delete this event!' => 'Non hai il permesso di cancellare questo evento!',
];
