<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Calendar</strong> module configuration' => '',
    'Adds an snippet with upcoming events to your users dashboard.' => '',
    'Half a year' => '',
    'If activated, the calendar top menu item and dashboard snippet is only visible for users having the calendar module installed in their profile.' => '',
    'Interval of upcoming events' => '',
    'Max event items' => '',
    'One month' => '',
    'One week' => '',
    'One year' => '',
    'Only show top menu item and snippet if the module is installed in the users profile' => '',
    'Show snippet' => '',
    'Sort order' => '',
    'Upcoming events snippet' => '',
];
