<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(disabled)' => '',
    'Here you can manage calendar types provided by other modules.' => '',
    'Other Calendars Configuration' => '',
    '(global)' => '(globale)',
    '<strong>Calendar</strong> module configuration' => 'Configurazione del modulo <strong>Calendario</strong> ',
    '<strong>Confirm</strong> Deletion' => '<strong>Conferma</strong> Cancellazione',
    'Adds an snippet with upcoming events to your users dashboard.' => 'Aggiunge un snippet con i prossimi eventi al dashboard degli utenti.',
    'Create new type' => 'Crea un nuovo tipo',
    'Default event settings' => 'Impostazione di Default',
    'Delete' => 'Cancella',
    'Do you really want to delte this event type?' => 'Vuoi davvero cancellare questo tipo di evento?',
    'Event Type Configuration' => 'Configurazione Tipo di Evento',
    'Half a year' => 'Semestre',
    'Here you can configure default settings for new calendar events.' => 'Qui è possibile configurare le impostazioni predefinite per i nuovi eventi del calendario.',
    'Here you can configure default settings for new calendar events. These settings can be overwritten on space/profile level.' => 'Qui è possibile configurare le impostazioni predefinite per i nuovi eventi del calendario. Queste impostazioni possono essere sovrascritte a livello di spazio/profilo.',
    'Here you can manage your event types.' => 'Qui è possibile gestire i tipi di eventi.',
    'If activated, the calendar top menu item and dashboard snippet is only visible for users having the calendar module installed in their profile.' => 'Se attivata, la voce di menu superiore del calendario e lo snippet del cruscotto sono visibili solo per gli utenti che hanno installato il modulo calendario nel loro profilo.',
    'Interval of upcoming events' => 'Intervallo eventi imminenti',
    'Max event items' => 'Numero massimo di eventi',
    'Name' => 'Nome',
    'One month' => 'Un mese',
    'One week' => 'Una settimana',
    'One year' => 'Un anno',
    'Only show top menu item and snippet if the module is installed in the users profile' => 'Mostra solo la voce di menu superiore e lo snippet solo se il modulo è installato nel profilo utente',
    'Reset' => 'Reimposta',
    'Show snippet' => 'Mostra snippet',
    'Sort order' => 'Ordina per',
    'There are currently no event types available.' => 'Attualmente non sono disponibili tipi di eventi.',
    'Upcoming events snippet' => 'snippet Eventi Imminenti',
];
