<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Add</strong> profile calendar' => '',
    'Are you sure you want to delete this event?' => '',
    'Attending' => '',
    'Close' => '',
    'Edit' => '',
    'Enable' => '',
    'In order to add events to your profile, you have to enable the calendar module first.' => '',
    'Interested' => '',
    'Invited' => '',
    'Next' => '',
    'Adds an calendar for private or public events to your profile and mainmenu.' => 'Добавляет календарь для лчиных или публичных событий в ваш профиль или в главное меню.',
    'Adds an event calendar to this space.' => 'Добавляет календарь к этому Пространству',
    'All Day' => 'Весь день',
    'Attending users' => 'Пользователи, которые собираются посетить событие',
    'Calendar' => 'Календарь',
    'Declining users' => 'Пользователи, которые отказались посетить событие',
    'Description' => 'Описание',
    'End Date' => 'Дата окончания',
    'End Time' => 'Время окончания',
    'End time must be after start time!' => 'Время окончания должно быть позже начала',
    'Event' => 'Событие',
    'Event not found!' => 'Событие не найдено!',
    'ID' => 'ID',
    'Maybe attending users' => 'Пользователи, которые возможно посетят событие',
    'Participation Mode' => 'Режим участия',
    'Public' => 'Публично',
    'Start Date' => 'Дата начала',
    'Start Time' => 'Время начала',
    'Title' => 'Наименование',
    'You don\'t have permission to delete this event!' => 'У вас нет доступа для удаления этого события!',
    'You don\'t have permission to edit this event!' => 'У вас нет доступа для редактирования этого события!',
];
