<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> event' => '<strong>Создать</strong> событие',
    '<strong>Edit</strong> event' => '<strong>Редактировать</strong> событие',
    '<strong>Note:</strong> This event will be created on your profile. To create a space event open the calendar on the desired space.' => '<strong>Внимание:</strong> это событие будет создано в вашем профиле. Чтобы создать событие для пространства, откройте календарь в желаемом пространстве',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'End Date/Time' => 'Дата/время окончания',
    'Everybody can participate' => 'Любой может принять участие',
    'No participants' => 'Нет участников',
    'Title' => 'Наименование',
];
