<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Filter</strong> events' => '<strong>Фильтровать</strong> события',
    '<strong>Select</strong> calendars' => '<strong>Выбор</strong> календаря',
    'Followed spaces' => 'Пространства, за которыми слежу',
    'Followed users' => 'Пользователи, за которыми слежу',
    'I\'m attending' => 'Я собираюсь посетить',
    'My events' => 'Мои события',
    'My profile' => 'Мой профиль',
    'My spaces' => 'Мои пространства',
];
