<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'End Time' => '',
    'Start Time' => '',
    'Adds an calendar for private or public events to your profile and mainmenu.' => 'Añade un calendario para eventos privados o publicos a tu perfil y menu principal.',
    'Adds an event calendar to this space.' => 'Añade un calendario de eventos a este espacio.',
    'All Day' => 'Todo el día',
    'Attending users' => 'Usuarios que asistirán',
    'Calendar' => 'Calendario',
    'Declining users' => 'Usuarios que no asistirán',
    'Description' => 'Descripción',
    'End Date' => 'Fecha de fin',
    'End time must be after start time!' => '¡La fecha de fin tiene que ser después de la fecha de inicio!',
    'Event' => 'Evento',
    'Event not found!' => '¡Evento no encontrado!',
    'ID' => 'ID',
    'Maybe attending users' => 'Usuarios que tal vez asistan',
    'Participation Mode' => 'Modo de participación',
    'Start Date' => 'Fecha de inicio',
    'Title' => 'Título',
    'You don\'t have permission to delete this event!' => '¡No tienes permisos para borrar este evento!',
    'You don\'t have permission to edit this event!' => '¡No tienes permisos para editar este evento!',
];
