<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(disabled)' => '',
    'Here you can manage calendar types provided by other modules.' => '',
    'Other Calendars Configuration' => '',
    '(global)' => '(global)',
    '<strong>Calendar</strong> module configuration' => 'Configuración del módulo de <strong>Calendario</strong>',
    '<strong>Confirm</strong> Deletion' => '<strong>Confirme</strong> borrado',
    'Adds an snippet with upcoming events to your users dashboard.' => 'Añade un snippet con próximos eventos al panel de control de sus usuarios.',
    'Create new type' => 'Crear tipo nuevo',
    'Default event settings' => 'Configuración por defecto de evento',
    'Delete' => 'Borrar',
    'Do you really want to delte this event type?' => '¿Está seguro de querer borrar este tipo?',
    'Event Type Configuration' => 'Configuración de tipo de evento',
    'Half a year' => 'Medio año',
    'Here you can configure default settings for new calendar events.' => 'Aquí puede configurar valores por defecto para nuevos eventos de calendario.',
    'Here you can configure default settings for new calendar events. These settings can be overwritten on space/profile level.' => 'Aquí puede configurar valores por defecto para nuevos eventos de calendario. Estos valores pueden modificarse en los espacios/perfiles.',
    'Here you can manage your event types.' => 'Aquí puede administrar sus tipos de evento.',
    'If activated, the calendar top menu item and dashboard snippet is only visible for users having the calendar module installed in their profile.' => 'Si se activa, sólo los usuarios que tengan instalado el módulo calendario en sus perfiles podrán ver el elemento Calendario en el menú superior y el snippet en su panel de control.',
    'Interval of upcoming events' => 'Intervalo de futuros eventos',
    'Max event items' => 'Máximo número de eventos',
    'Name' => 'Nombre',
    'One month' => 'Un mes',
    'One week' => 'Una semana',
    'One year' => 'Un año',
    'Only show top menu item and snippet if the module is installed in the users profile' => 'Mostrar el elemento en el menú superior y el snippet sólo si el módulo está instalado en el perfil del usuario',
    'Reset' => 'Borrar',
    'Show snippet' => 'Mostrar snippet',
    'Sort order' => 'Ordenado por',
    'There are currently no event types available.' => 'Ahora mismo no hay tipos de evento disponibles.',
    'Upcoming events snippet' => 'Snippet de próximos eventos',
];
