<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Filter</strong> events' => '<strong>筛选</strong> 事件',
    '<strong>Select</strong> calendars' => '<strong>选择</strong> 日历',
    'Followed spaces' => '关注的版块',
    'Followed users' => '关注的用户',
    'I\'m attending' => '我参加',
    'My events' => '我的事件',
    'My profile' => '我的属性',
    'My spaces' => '我的版块',
];
