<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Add</strong> profile calendar' => '',
    'Are you sure you want to delete this event?' => '',
    'Attending' => '',
    'Close' => '',
    'Edit' => '',
    'Enable' => '',
    'In order to add events to your profile, you have to enable the calendar module first.' => '',
    'Interested' => '',
    'Invited' => '',
    'Next' => '',
    'Public' => '',
    'Adds an calendar for private or public events to your profile and mainmenu.' => 'あなたのプロフィールやメインメニューに、プライベートまたは公開イベントカレンダーを追加します。',
    'Adds an event calendar to this space.' => 'このスペースにイベントカレンダーを追加します。',
    'All Day' => '終日',
    'Attending users' => '参加者',
    'Calendar' => 'カレンダー',
    'Declining users' => 'ユーザー数の減少',
    'Description' => '説明',
    'End Date' => '終了日',
    'End Time' => '終了時間',
    'End time must be after start time!' => '終了時刻は開始時刻より後になるように設定してください！',
    'Event' => 'イベント',
    'Event not found!' => 'イベントが見つかりません！',
    'ID' => 'ID',
    'Maybe attending users' => '参加予定者',
    'Participation Mode' => '参加方法',
    'Start Date' => '開始日',
    'Start Time' => '開始時間',
    'Title' => 'タイトル',
    'You don\'t have permission to delete this event!' => 'あなたはこのイベントの削除権限がありません',
    'You don\'t have permission to edit this event!' => 'あなたはこのイベントの編集権限がありません',
];
