<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> event' => '<strong>作成</strong> イベントの作成',
    '<strong>Edit</strong> event' => '<strong>編集</strong> イベントの編集',
    '<strong>Note:</strong> This event will be created on your profile. To create a space event open the calendar on the desired space.' => '<strong>注：</strong>のこのイベントは、あなたのプロフィール上に作成されます。スペース内のイベントを作成するには、目的のスペースのカレンダーを開きます。',
    'Delete' => '削除',
    'Description' => '説明',
    'End Date/Time' => '終了日時',
    'Everybody can participate' => '誰もが参加できる',
    'No participants' => '参加しない',
    'Title' => 'タイトル',
];
