<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'End Time' => '',
    'Start Time' => '',
    'Adds an calendar for private or public events to your profile and mainmenu.' => 'Į Jūsu profilį prideda viešu ir privačiu renginiu kalendoriu.',
    'Adds an event calendar to this space.' => 'Šiai erdvei prideda renginiu kalendoriu.',
    'All Day' => 'Visa diena',
    'Attending users' => 'Dalyvaujantys vartotojai',
    'Calendar' => 'Kalendorius',
    'Declining users' => 'Nedalyvaujantys vartotojai',
    'Description' => 'Apibūdinimas',
    'End Date' => 'Pabaigos data',
    'End time must be after start time!' => 'Pabaigos laikas turi būti po pradžios laiko!',
    'Event' => 'Įvykis',
    'Event not found!' => 'Renginys nerastas!',
    'ID' => 'ID',
    'Maybe attending users' => 'Galbūt dalyvausiantys vartotojai',
    'Participation Mode' => 'Dalyvavimo būsena',
    'Start Date' => 'Pradžios data',
    'Title' => 'Pavadinimas ',
    'You don\'t have permission to delete this event!' => 'Jūs neturite leidimo ištrinti šį įvykį ! ',
    'You don\'t have permission to edit this event!' => 'Jūs neturite leidimo redaguoti šį įvykį ! ',
];
