<?php

/**
 * @link https://www.humhub.org/
 * @copyright Copyright (c) HumHub GmbH & Co. KG
 * @license https://www.humhub.com/licences
 */

namespace humhub\modules\calendar\extensions\custom_pages\elements;

use DateInterval;
use DateTime;
use humhub\helpers\Html;
use humhub\modules\calendar\helpers\CalendarUtils;
use humhub\modules\calendar\helpers\RecurrenceHelper;
use humhub\modules\calendar\models\CalendarEntry;
use humhub\modules\calendar\models\CalendarEntryParticipant;
use humhub\modules\content\components\ActiveQueryContent;
use humhub\modules\custom_pages\modules\template\elements\BaseContentRecordsElement;
use humhub\modules\custom_pages\modules\template\elements\BaseElementVariable;
use humhub\widgets\form\ActiveForm;
use Throwable;
use Yii;
use yii\db\ActiveQuery;

/**
 * Class to manage content records of the elements with Calendar events list
 *
 * @property int $nextDays
 */
class CalendarEventsElement extends BaseContentRecordsElement
{
    public const FILTER_PARTICIPANT = 'participant';
    public const FILTER_PAST = 'past_events';
    public const RECORD_CLASS = CalendarEntry::class;
    public const SORT_UPCOMING = 'upcoming';

    /**
     * @var CalendarEntry[]|null resolved (and possibly dynamically expanded/virtual) records, see [[getItems()]]
     */
    protected ?array $expandedRecords = null;

    /**
     * @inheritdoc
     */
    protected function getDynamicAttributes(): array
    {
        return array_merge(parent::getDynamicAttributes(), [
            'nextDays' => null,
        ]);
    }

    /**
     * @inheritdoc
     */
    public function getLabel(): string
    {
        return Yii::t('CalendarModule.base', 'Calendar events');
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return array_merge(parent::attributeLabels(), [
            'nextDays' => Yii::t('CalendarModule.base', 'Display events within the next X days'),
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'nextDays' => Yii::t('CalendarModule.base', 'Leave empty to list all events. Enter 0 to display only today\'s events.'),
        ]);
    }

    /**
     * @inheritdoc
     */
    public function getContentFilterOptions(): array
    {
        return array_merge([
            self::FILTER_PAST => Yii::t('CalendarModule.base', 'Show past events'),
            self::FILTER_PARTICIPANT => Yii::t('CalendarModule.base', 'I\'m attending'),
        ], parent::getContentFilterOptions());
    }

    /**
     * Whether the "By upcoming events first" sort option (or its deprecated 'date_new'
     * alias) is currently selected.
     *
     * @return bool
     */
    protected function isUpcomingSorting(): bool
    {
        return in_array($this->sortOrder, [self::SORT_UPCOMING, 'date_new'/* support deprecated */]);
    }

    /**
     * @inheritdoc
     *
     * Note: this only queries the recurrence "root" entries (or plain non-recurring
     * entries). The actual occurrences of a recurring event are not necessarily
     * persisted as their own `calendar_entry` record, so they are dynamically
     * expanded - just like in the regular Calendar views - in [[getItems()]].
     *
     * @return ActiveQueryContent
     */
    protected function getQuery(): ActiveQuery
    {
        $query = parent::getQuery();

        // Recurrence instances are (re-)generated by expanding their recurrence root
        // in getItems(), so already persisted/materialized instances must be excluded
        // here, otherwise they would be listed twice (see humhub/calendar#712).
        $query->andWhere(['calendar_entry.parent_event_id' => null]);

        if (!Yii::$app->user->isGuest && $this->hasFilter(self::FILTER_PARTICIPANT)) {
            $query->leftJoin('calendar_entry_participant', 'calendar_entry.id = calendar_entry_participant.calendar_entry_id AND calendar_entry_participant.user_id = :userId', [':userId' => Yii::$app->user->id])
                ->andWhere(['calendar_entry_participant.participation_state' => CalendarEntryParticipant::PARTICIPATION_STATE_ACCEPTED]);
        }

        $isUpcomingSorting = $this->isUpcomingSorting();

        // Note: recurring root entries are exempted from the date-range filters below.
        // Their own start/end date may already lie outside of the requested range even
        // though the series still produces occurrences within it (e.g. an old weekly
        // meeting which is still ongoing). The actual date filtering of the individual
        // occurrences happens after expanding the recurrence, see filterByDate().
        if (!$this->hasFilter(self::FILTER_PAST) || $isUpcomingSorting) {
            $now = new DateTime('now', CalendarUtils::getUserTimeZone());
            $query->andWhere(['or',
                ['>', 'calendar_entry.end_datetime', $now->format('Y-m-d H:i:s')],
                ['not', ['calendar_entry.rrule' => null]],
            ]);
        }

        if ($this->nextDays !== null && $this->nextDays !== '') {
            $maxDate = new DateTime('+' . ($this->nextDays + 1) . ' days', CalendarUtils::getUserTimeZone());
            $query->andWhere(['or',
                ['<', 'calendar_entry.start_datetime', $maxDate->format('Y-m-d')],
                ['not', ['calendar_entry.rrule' => null]],
            ]);
        }

        if ($isUpcomingSorting) {
            $query->orderBy(['calendar_entry.start_datetime' => SORT_ASC]);
        }

        // The limit is applied after expanding recurrences and sorting the resulting
        // occurrences in getItems(). Limiting on the amount of root/series records
        // here could otherwise hide occurrences which would actually be eligible for
        // the list (e.g. a single old recurring series could occupy the whole limit
        // even though only one of its many expanded instances is actually relevant).
        return $query->limit(null);
    }

    /**
     * @inheritdoc
     *
     * Expands recurring events into their actual occurrences within the relevant
     * time frame - just like the regular Calendar views do - since only the original
     * event of a recurring series is persisted as its own `calendar_entry` record
     * (see humhub/calendar#712).
     */
    public function getItems(): iterable
    {
        if ($this->expandedRecords === null) {
            $this->expandedRecords = $this->expandRecords($this->getQuery()->all());
        }

        yield from $this->expandedRecords;
    }

    /**
     * Expands recurring root entries of the given records into their actual
     * occurrences and re-applies the date/sort/limit options on the resulting flat
     * list of (partly virtual, not necessarily persisted) [[CalendarEntry]] items.
     *
     * @param CalendarEntry[] $records
     * @return CalendarEntry[]
     */
    protected function expandRecords(array $records): array
    {
        [$from, $to] = $this->getExpandRange();

        $result = [];
        foreach ($records as $record) {
            if (RecurrenceHelper::isRecurrentRoot($record)) {
                try {
                    // Note: $save is intentionally false here, we do not want to persist
                    // new calendar_entry records for every rendering of this element.
                    $record->getRecurrenceQuery()->expandEvent($from, $to, false, $result);
                } catch (Throwable $e) {
                    Yii::error('Could not expand recurring calendar event #' . $record->id . ': ' . $e->getMessage(), 'calendar');
                }

                continue;
            }

            $result[] = $record;
        }

        $result = $this->filterByDate($result);
        $result = $this->filterResolvableRoots($result);

        if ($this->isUpcomingSorting()) {
            // "By upcoming events first" always reads chronologically by start date,
            // regardless of when the underlying content was created/updated.
            usort($result, fn(CalendarEntry $a, CalendarEntry $b) => $a->getStartDateTime() <=> $b->getStartDateTime());
        } else {
            // Once recurring events are expanded into their individual occurrences, a
            // plain sort by content creation/update date (see getContentSortValue())
            // would leave the relative order *within* a group of occurrences sharing
            // that same date (i.e. the same recurring series - that date describes the
            // series as a whole, not a single occurrence) essentially undefined. A
            // start date tie-breaker keeps those occurrences chronological within
            // their own group (see humhub/calendar#712).
            usort($result, function (CalendarEntry $a, CalendarEntry $b) {
                $cmp = ($this->getContentSortValue($b) ?? '') <=> ($this->getContentSortValue($a) ?? '');

                return $cmp !== 0 ? $cmp : ($a->getStartDateTime() <=> $b->getStartDateTime());
            });
        }

        // Leaving "limit" empty means "list all events" - within the expand window
        // (see getExpandRange(): bounded by "Display events within the next X days",
        // or a 1 year default for recurring events if that is left empty too).
        if (!empty($this->limit)) {
            $result = array_slice($result, 0, (int) $this->limit);
        }

        return $result;
    }

    /**
     * Resolves the real content creation/update timestamp backing the selected
     * "sortOrder" option (see [[BaseContentRecordsElement::getQuery()]]) for the given
     * (possibly virtual/expanded) record.
     *
     * A dynamically expanded recurrence instance is not persisted as its own
     * `calendar_entry`/Content record (see humhub/calendar#712) and thus has no real
     * content timestamps of its own - the timestamp of its recurrence root is used
     * instead, since it conceptually describes the recurring series as a whole.
     *
     * @param CalendarEntry $record
     * @return string|null
     */
    protected function getContentSortValue(CalendarEntry $record): ?string
    {
        $source = $record;

        if ($record->isNewRecord && RecurrenceHelper::isRecurrentInstance($record)) {
            $source = $record->getRecurrenceRoot();
        }

        if (!$source) {
            return null;
        }

        return $this->sortOrder === self::SORT_UPDATE
            ? $source->content->stream_sort_date
            : $source->content->created_at;
    }

    /**
     * Excludes virtual (not yet persisted) recurrence instances whose recurrence root
     * can no longer be resolved - this should not normally happen (the root was read
     * from the database just before being expanded, a few lines above), but could
     * theoretically occur if the whole recurring series got deleted concurrently while
     * this list was being built. [[CalendarEntryElementVariable]] relies on the root
     * being resolvable (it has no Content of its own to fall back to), so such an
     * instance is dropped here rather than rendered with faked/placeholder Content data.
     *
     * @param CalendarEntry[] $records
     * @return CalendarEntry[]
     */
    protected function filterResolvableRoots(array $records): array
    {
        return array_values(array_filter($records, function (CalendarEntry $record) {
            if ($record->isNewRecord && RecurrenceHelper::isRecurrentInstance($record) && !$record->getRecurrenceRoot()) {
                Yii::warning('Skipping a virtual calendar entry instance without a resolvable recurrence root (likely deleted concurrently).', 'calendar');
                return false;
            }

            return true;
        }));
    }

    /**
     * Applies the same "Show past events" / "next X days" semantics used in [[getQuery()]]
     * on the given (expanded) records, since those filters could not be fully applied at
     * the SQL level for recurring events.
     *
     * @param CalendarEntry[] $records
     * @return CalendarEntry[]
     */
    protected function filterByDate(array $records): array
    {
        $isUpcomingSorting = $this->isUpcomingSorting();
        $now = new DateTime('now', CalendarUtils::getUserTimeZone());

        $maxDate = null;
        if ($this->nextDays !== null && $this->nextDays !== '') {
            $maxDate = new DateTime('+' . ($this->nextDays + 1) . ' days', CalendarUtils::getUserTimeZone());
        }

        $showPast = $this->hasFilter(self::FILTER_PAST) && !$isUpcomingSorting;

        return array_values(array_filter($records, function (CalendarEntry $record) use ($showPast, $now, $maxDate) {
            if (!$showPast && $record->getEndDateTime() <= $now) {
                return false;
            }

            if ($maxDate !== null && $record->getStartDateTime() >= $maxDate) {
                return false;
            }

            return true;
        }));
    }

    /**
     * Determines the time frame recurring events should be expanded within, based on
     * the "Show past events" and "next X days" options of this element.
     *
     * @return DateTime[] a two value array of [$from, $to]
     */
    protected function getExpandRange(): array
    {
        $tz = CalendarUtils::getUserTimeZone();

        $from = $this->hasFilter(self::FILTER_PAST)
            ? (new DateTime('now', $tz))->sub(new DateInterval('P1Y'))
            : new DateTime('now', $tz);

        $to = ($this->nextDays !== null && $this->nextDays !== '')
            ? new DateTime('+' . ($this->nextDays + 1) . ' days', $tz)
            : (new DateTime('now', $tz))->add(new DateInterval('P1Y'));

        return [$from, $to];
    }

    /**
     * @inheritdoc
     */
    public function getTemplateVariable(): BaseElementVariable
    {
        return new CalendarEventsElementVariable($this);
    }

    /**
     * @inheritdoc
     */
    public function renderEditForm(ActiveForm $form): string
    {
        $sortUpcoming = self::SORT_UPCOMING;
        $filterPast = self::FILTER_PAST;

        return parent::renderEditForm($form)
            . $form->field($this, 'nextDays')
            // Disable filter "Show past events" on sorting "By upcoming events first":
            . Html::script(<<<JS
var calendarsSortOrderSelector = 'input[name="CalendarEventsElement[sortOrder]"]';
if (typeof changeCalendarsElementFilter === 'undefined') {
    function changeCalendarsElementFilter() {
        const sortOrder = document.querySelector(calendarsSortOrderSelector + ':checked');
        const pastEvents = document.querySelector('input[name="CalendarEventsElement[filter][]"][value="{$filterPast}"]');
        if (sortOrder && pastEvents) {
            pastEvents.disabled = sortOrder.value === '{$sortUpcoming}';
        }
    }
}

changeCalendarsElementFilter();
document.querySelectorAll(calendarsSortOrderSelector).forEach(el => {
    el.addEventListener('change', changeCalendarsElementFilter);
});
JS);
    }

    /**
     * @inheritdoc
     */
    protected function getSortOptions(): array
    {
        return array_merge(parent::getSortOptions(), [
            self::SORT_UPCOMING => Yii::t('CalendarModule.base', 'By upcoming events first'),
        ]);
    }
}
