<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Adds an calendar for private or public events to your profile and mainmenu.' => '',
  'Adds an event calendar to this space.' => '',
  'All Day' => '',
  'Attending users' => '',
  'Calendar' => '',
  'Declining users' => '',
  'Description' => '',
  'End Date' => '',
  'End Date and Time' => '',
  'End time must be after start time!' => '',
  'Event' => '',
  'Event not found!' => '',
  'ID' => '',
  'Maybe attending users' => '',
  'Participation Mode' => '',
  'Recur' => '',
  'Recur End' => '',
  'Recur Interval' => '',
  'Recur Type' => '',
  'Select participants' => '',
  'Start Date' => '',
  'Start Date and Time' => '',
  'Title' => '',
  'You don\'t have permission to access this event!' => '',
  'You don\'t have permission to create events!' => '',
  'You don\'t have permission to delete this event!' => '',
  'You don\'t have permission to edit this event!' => '',
);
