<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Add</strong> profile calendar' => '',
    '<strong>Choose</strong> target calendar' => '',
    'Allow participation state \'decline\'' => '',
    'Allow participation state \'maybe\'' => '',
    'Attending' => '',
    'Birthday' => '',
    'Cancel Event' => '',
    'Close' => '',
    'Download as ICS file' => '',
    'Event Type' => '',
    'Event type color' => '',
    'In order to add events to your profile, you have to enable the calendar module first.' => '',
    'Invalid event type id selected.' => '',
    'Maximum number of participants' => '',
    'Profile Calendar' => '',
    'Reopen Event' => '',
    'Send update notification' => '',
    'Time Zone' => '',
    'canceled' => '',
    '{displayName} Birthday' => '',
    'Adds a calendar for private or public events to your profile and main menu.' => 'Profilinize ve ana menünüze etkinlikler için bir takvim ekler.',
    'Adds an event calendar to this space.' => 'Bu mekana bir etkinlik takvimi ekler.',
    'All Day' => 'Tüm günler',
    'Attending users' => 'Katılanlar',
    'Calendar' => 'Takvim',
    'Declining users' => 'Katılmayanlar',
    'Description' => 'Açıklama',
    'Edit' => 'Düzenle',
    'Enable' => 'Etkinleştirme',
    'End Date' => 'Bitiş tarihi',
    'End Time' => 'Bitiş Zamanı',
    'End time must be after start time!' => 'Bitiş saati başlangıç ​​zamanından sonra olmalıdır!',
    'Event' => 'Etkinlik',
    'Event not found!' => 'Etkinlik bulunamadı!',
    'ID' => 'Kimlik',
    'Interested' => 'İlgilenen',
    'Maybe attending users' => 'Belki katılanlar',
    'Next' => 'İleri',
    'Participation Mode' => 'Katılım şekli',
    'Public' => 'Herkese açık',
    'Start Date' => 'Başlangıç tarihi',
    'Start Time' => 'Başlangıç Zamanı',
    'Title' => 'Başlık',
    'You don\'t have permission to delete this event!' => 'Bu etkinliği silmek için izniniz yok!',
];
