<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> event' => '<strong>Etkinlik</strong> oluştur',
    '<strong>Edit</strong> event' => '<strong>Etkinlik</strong> düzenle',
    '<strong>Note:</strong> This event will be created on your profile. To create a space event open the calendar on the desired space.' => '<strong>Not:</strong> Bu etkinlik profilinizde oluşturulur. Eğer mekanda etkinlik açmak istiyorsanız mekan takvimini kullanın.',
    'Delete' => 'Sil',
    'Description' => 'Açıklama',
    'End Date/Time' => 'Bitiş tarih/saat',
    'Everybody can participate' => 'Herkes katılabilir',
    'No participants' => 'Katılımsız',
    'Title' => 'Başlık',
];
