<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cancel Event' => '',
    'Reopen Event' => '',
    '<strong>Add</strong> profile calendar' => '<strong>Ajouter</strong> un calendrier au profil',
    '<strong>Choose</strong> target calendar' => '<strong>Choisir</strong> le calendrier de destination',
    'Adds a calendar for private or public events to your profile and main menu.' => 'Ce module permet d\'ajouter un calendrier pour les événements privés ou publics à votre profil et au menu principal.',
    'Adds an event calendar to this space.' => 'Ce module permet d\'ajouter un calendrier à cet espace.',
    'All Day' => 'Toute la journée',
    'Allow participation state \'decline\'' => 'Autoriser le statut de participation "décline"',
    'Allow participation state \'maybe\'' => 'Autoriser le statut de participation "peut-être"',
    'Attending' => 'Participe',
    'Attending users' => 'Membres ayant confirmés leur participation',
    'Birthday' => 'Anniversaire',
    'Calendar' => 'Calendrier',
    'Close' => 'Fermer',
    'Declining users' => 'Membres ayant déclinés leur participation',
    'Description' => 'Description',
    'Download as ICS file' => 'Télécharger',
    'Edit' => 'Modifier',
    'Enable' => 'Activer',
    'End Date' => 'Date de fin',
    'End Time' => 'Heure de fin',
    'End time must be after start time!' => 'L\'heure de fin doit être après l\'heure de début.',
    'Event' => 'Événement',
    'Event Type' => 'Type d\'événement',
    'Event not found!' => 'Événement introuvable.',
    'Event type color' => 'Couleur du type d\'événement',
    'ID' => 'ID',
    'In order to add events to your profile, you have to enable the calendar module first.' => 'Pour ajouter des événements à votre profil, vous devez d\'abord activer le module calendrier.',
    'Interested' => 'Intéressé',
    'Invalid event type id selected.' => 'ID du type d’événement sélectionné invalide.',
    'Maximum number of participants' => 'Nombre maximum de participants',
    'Maybe attending users' => 'Les membres qui participeront peut-être',
    'Next' => 'Suivant',
    'Participation Mode' => 'Mode de participation',
    'Profile Calendar' => 'Calendrier du profil',
    'Public' => 'Public',
    'Send update notification' => 'Envoyer une notification pour cette modification',
    'Start Date' => 'Date de début',
    'Start Time' => 'Heure de début',
    'Time Zone' => 'Fuseau Horaire',
    'Title' => 'Titre',
    'You don\'t have permission to delete this event!' => 'Vous n\'avez pas les permissions pour effacer cet événement.',
    'canceled' => 'annulé',
    '{displayName} Birthday' => 'Anniversaire de {displayName}',
];
