<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Add</strong> profile calendar' => '',
    'Are you sure you want to delete this event?' => '',
    'Attending' => '',
    'Close' => '',
    'Edit' => '',
    'Enable' => '',
    'In order to add events to your profile, you have to enable the calendar module first.' => '',
    'Interested' => '',
    'Invited' => '',
    'Next' => '',
    'Public' => '',
    'Adds an calendar for private or public events to your profile and mainmenu.' => 'Ajoute un calendrier pour les événements privés ou publics à votre profil et au menu principal',
    'Adds an event calendar to this space.' => 'Ajoute un calendrier à cet espace.',
    'All Day' => 'Toute la journée',
    'Attending users' => 'Utilisateurs participants',
    'Calendar' => 'Calendrier',
    'Declining users' => 'Participants ayant décliné l\'invitation',
    'Description' => 'Description',
    'End Date' => 'Date de fin',
    'End Time' => 'Heure de fin',
    'End time must be after start time!' => 'L\'heure de fin doit être après l\'heure de début !',
    'Event' => 'Événement',
    'Event not found!' => 'Événement introuvable !',
    'ID' => 'ID',
    'Maybe attending users' => 'Probablement en attente de participants',
    'Participation Mode' => 'Mode de participation',
    'Start Date' => 'Date de début',
    'Start Time' => 'Heure de début',
    'Title' => 'Titre',
    'You don\'t have permission to delete this event!' => 'Vous n\'avez pas le droit d\'effacer cet événement !',
    'You don\'t have permission to edit this event!' => 'Vous n\'avez pas le droit de modifier cet événement !',
];
