<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(global)' => '',
    '<strong>Calendar</strong> module configuration' => 'Configuration du module <strong>Calendrier</strong>',
    '<strong>Confirm</strong> Deletion' => '<strong>Confirmer</strong>Suppression',
    'Adds an snippet with upcoming events to your users dashboard.' => 'Ajoute un extrait avec les prochains événements à votre tableau des utilisateurs.',
    'Create new type' => 'Créer un nouveau type',
    'Default event settings' => 'Paramètres de l\'événement par défaut',
    'Delete' => 'Suprimer',
    'Do you really want to delte this event type?' => 'Voulez vous déjà supprimer ce type d\'événement ?',
    'Event Type Configuration' => 'Configuration du type d\'événement',
    'Half a year' => 'Six mois',
    'Here you can configure default settings for new calendar events.' => 'Ici vous pouvez configurer les paramètres par défaut pour un nouveau calendrier d\'événements',
    'Here you can configure default settings for new calendar events. These settings can be overwritten on space/profile level.' => 'Ici vous pouvez configurer les paramètres par défaut pour un nouveau calendrier d\'événements. Ces paramètres peuvent êtres modifiés via espaces/profil.',
    'Here you can manage your event types.' => 'Ici vous pouvez contrôler vos type d\'événement. ',
    'If activated, the calendar top menu item and dashboard snippet is only visible for users having the calendar module installed in their profile.' => 'Si activé, l\'élément calendrier du menu et l\'extrait sur le tableau de bord sont uniquement visibles par les utilisateurs qui ont installé le module calendrier dans leur profil.',
    'Interval of upcoming events' => 'Intervalle des prochains événements',
    'Max event items' => 'Nombre maximum d\'éléments',
    'Name' => 'Nom',
    'One month' => 'Un mois',
    'One week' => 'Une semaine',
    'One year' => 'Un an',
    'Only show top menu item and snippet if the module is installed in the users profile' => 'Afficher uniquement l\'élément calendrier du menu et l\'extrait sur le tableau de bord si le module calendrier est installé dans le profil des utilisateurs.',
    'Reset' => 'réinitialiser',
    'Show snippet' => 'Afficher un extrait',
    'Sort order' => 'Ordre de tri',
    'There are currently no event types available.' => 'Il n\'y a aucun type d\'événement disponible pour le moment.',
    'Upcoming events snippet' => 'Extrait des prochains événements',
];
