<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> event' => '<strong>Créer</strong> un événement',
    '<strong>Edit</strong> event' => '<strong>Editer</strong> un événement',
    '<strong>Note:</strong> This event will be created on your profile. To create a space event open the calendar on the desired space.' => '<strong>Note :</strong> Cet événement sera créé dans votre profil. Pour créer un événement dans un espace, ouvrez le calendrier de l\'espace concerné.',
    'Delete' => 'Effacer',
    'Description' => 'Description',
    'End Date/Time' => 'Heure et date de fin',
    'Everybody can participate' => 'Tout le monde peut participer',
    'No participants' => 'Pas de participant',
    'Title' => 'Titre',
];
