<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Filter</strong> events' => '<strong>Filtrer</strong> les événements',
    '<strong>Select</strong> calendars' => '<strong>Choisir</strong> les calendriers',
    'Followed spaces' => 'Espaces suivis',
    'Followed users' => 'Utilisateurs suivis',
    'I\'m attending' => 'Je participe',
    'My events' => 'Mes événements',
    'My profile' => 'Mon profil',
    'My spaces' => 'Mes espaces',
];
