<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Add</strong> profile calendar' => '',
    'Are you sure you want to delete this event?' => '',
    'Attending' => '',
    'Close' => '',
    'Edit' => '',
    'Enable' => '',
    'In order to add events to your profile, you have to enable the calendar module first.' => '',
    'Interested' => '',
    'Invited' => '',
    'Next' => '',
    'Public' => '',
    'Adds an calendar for private or public events to your profile and mainmenu.' => 'Adicione um calendário para eventos privados ou públicos em seu perfil e menu principal.',
    'Adds an event calendar to this space.' => 'Adicione um evento para este espaço.',
    'All Day' => 'Todo dia',
    'Attending users' => 'Confirmaram presença',
    'Calendar' => 'Calendário ',
    'Declining users' => 'Não Confirmaram presença',
    'Description' => 'Descrição',
    'End Date' => 'Data Final',
    'End Time' => 'Hora de término',
    'End time must be after start time!' => 'A hora de término precisa ser depois da hora de início!',
    'Event' => 'Evento',
    'Event not found!' => 'Evento não encontrado!',
    'ID' => 'ID',
    'Maybe attending users' => 'Talvez marcarão presença',
    'Participation Mode' => 'Modo de Participação',
    'Start Date' => 'Data de Inicio',
    'Start Time' => 'Hora de início',
    'Title' => 'Título',
    'You don\'t have permission to delete this event!' => 'Você não tem permissão para apagar este evento!',
    'You don\'t have permission to edit this event!' => 'Você não tem permissão para editar este evento!',
];
