<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Choose</strong> target calendar' => '',
    'Birthday' => '',
    'Cancel Event' => '',
    'Download as ICS file' => '',
    'Profile Calendar' => '',
    'Reopen Event' => '',
    '{displayName} Birthday' => '',
    '<strong>Add</strong> profile calendar' => '<strong>Adicionar</strong> calendário de perfil',
    'Adds a calendar for private or public events to your profile and main menu.' => 'Adicione um calendário para eventos privados ou públicos em seu perfil e menu principal.',
    'Adds an event calendar to this space.' => 'Adicione um evento para este espaço.',
    'All Day' => 'Todo dia',
    'Allow participation state \'decline\'' => 'Permitir estado de participação \'negar\'',
    'Allow participation state \'maybe\'' => 'Permitir estado de participação \'talvez\'',
    'Attending' => 'Comparecendo',
    'Attending users' => 'Usuários que comparecerão',
    'Calendar' => 'Calendário',
    'Close' => 'Fechar',
    'Declining users' => 'Usuários que recusaram',
    'Description' => 'Descrição',
    'Edit' => 'Editar',
    'Enable' => 'Habilitar',
    'End Date' => 'Data Final',
    'End Time' => 'Hora de término',
    'End time must be after start time!' => 'A hora de término precisa ser depois da hora de início!',
    'Event' => 'Evento',
    'Event Type' => 'Tipo de Evento',
    'Event not found!' => 'Evento não encontrado!',
    'Event type color' => 'Cor do tipo de evento',
    'ID' => 'ID',
    'In order to add events to your profile, you have to enable the calendar module first.' => 'Para poder adicionar eventos ao seu perfil, você precisa habilitar o módulo de calendário primeiro',
    'Interested' => 'Interessado',
    'Invalid event type id selected.' => 'Tipo de evento selecionado é inválido',
    'Maximum number of participants' => 'Número máximo de participantes',
    'Maybe attending users' => 'Usuários que talvez comparecerão',
    'Next' => 'Próximo',
    'Participation Mode' => 'Modo de Participação',
    'Public' => 'Público',
    'Send update notification' => 'Enviar notificação de atualização',
    'Start Date' => 'Data de Inicio',
    'Start Time' => 'Hora de início',
    'Time Zone' => 'Fuso Horário',
    'Title' => 'Título',
    'You don\'t have permission to delete this event!' => 'Você não tem permissão para apagar este evento!',
    'canceled' => 'cancelado',
];
