<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'End Time' => '',
    'Start Time' => '',
    'End Date and Time' => 'Data e hora final',
    'Recur' => 'Lembrete',
    'Recur End' => 'Final do lembrete',
    'Recur Interval' => 'Intervalo do lembrete',
    'Recur Type' => 'Tipo de lembrete',
    'Select participants' => 'Selecionar participantes',
    'Start Date and Time' => 'Data e hora inicial',
    'You don\'t have permission to access this event!' => 'Você não tem permissão para acessar este evento!',
    'You don\'t have permission to create events!' => 'Você não tem permissão para criar eventos!',
    'Adds an calendar for private or public events to your profile and mainmenu.' => 'Adicione um calendário para eventos privados ou públicos em seu perfil e menu principal.',
    'Adds an event calendar to this space.' => 'Adicione um evento para este espaço.',
    'All Day' => 'Todo dia',
    'Attending users' => 'Confirmaram presença',
    'Calendar' => 'Calendário ',
    'Declining users' => 'Não Confirmaram presença',
    'Description' => 'Descrição',
    'End Date' => 'Data Final',
    'End time must be after start time!' => 'A hora final precisa ser depois da hora inicial!',
    'Event' => 'Evento',
    'Event not found!' => 'Evento não encontrado!',
    'ID' => 'ID',
    'Maybe attending users' => 'Talvez marcarão presença',
    'Participation Mode' => 'Modo de Participação',
    'Start Date' => 'Data de Inicio',
    'Title' => 'Título',
    'You don\'t have permission to delete this event!' => 'Você não tem permissão para apagar este evento!',
    'You don\'t have permission to edit this event!' => 'Você não tem permissão para editar este evento!',
];
