<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(disabled)' => '',
    'Here you can manage calendar types provided by other modules.' => '',
    'Other Calendars Configuration' => '',
    '(global)' => '(global)',
    '<strong>Calendar</strong> module configuration' => 'Módulo de configuração de <strong>Calendário</strong>',
    '<strong>Confirm</strong> Deletion' => '<strong>Confirmar</strong> exclusão',
    'Adds an snippet with upcoming events to your users dashboard.' => 'Adiciona um fragmento com eventos futuros ao seu painel de usuários.',
    'Create new type' => 'Criar novo tipo',
    'Default event settings' => 'Configurações de evento padrão',
    'Delete' => 'Apagar',
    'Do you really want to delte this event type?' => 'Você realmente quer apagar esse tipo de evento?',
    'Event Type Configuration' => 'Configuração de Tipo de Evento',
    'Half a year' => 'Metade de um ano',
    'Here you can configure default settings for new calendar events.' => 'Aqui você pode definir configurações padrão para novos eventos de calendário.',
    'Here you can configure default settings for new calendar events. These settings can be overwritten on space/profile level.' => 'Aqui você pode definir configurações padrão para novos eventos de calendário. Essas configurações podem ser sobrescritas em nível de perfil/espaço.',
    'Here you can manage your event types.' => 'Aqui você pode administrar seus tipos de eventos.',
    'If activated, the calendar top menu item and dashboard snippet is only visible for users having the calendar module installed in their profile.' => 'Se ativado, o menu superior e o fragmento de painel de calendário só será visível para usuários que possuem o módulo instalado em seu perfil.',
    'Interval of upcoming events' => 'Intervalo de eventos futuros.',
    'Max event items' => 'Máximo de itens de evento',
    'Name' => 'Nome',
    'One month' => 'Um mês',
    'One week' => 'Uma semana',
    'One year' => 'Um ano',
    'Only show top menu item and snippet if the module is installed in the users profile' => 'Somente exibir o menu superior e o fragmento se o módulo de calendário estiver instalado no perfil do usuário',
    'Reset' => 'Redefinir',
    'Show snippet' => 'Exibir fragmento',
    'Sort order' => 'Ordenação',
    'There are currently no event types available.' => 'No momento não há tipos de evento disponíveis.',
    'Upcoming events snippet' => 'Fragmento de eventos futuros',
];
