<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Add</strong> profile calendar' => '',
    'Are you sure you want to delete this event?' => '',
    'Attending' => '',
    'Close' => '',
    'Edit' => '',
    'Enable' => '',
    'End Time' => '',
    'In order to add events to your profile, you have to enable the calendar module first.' => '',
    'Interested' => '',
    'Invited' => '',
    'Next' => '',
    'Public' => '',
    'Start Time' => '',
    'Adds an calendar for private or public events to your profile and mainmenu.' => '在主菜单和个人属性页为你的私有或公共事件增加一个日历。',
    'Adds an event calendar to this space.' => '为这个版块增加一个事件日历。',
    'All Day' => '全天',
    'Attending users' => '参加用户',
    'Calendar' => '日历',
    'Declining users' => '拒绝用户',
    'Description' => '描述',
    'End Date' => '结束日期',
    'End time must be after start time!' => '结束时间必须晚于开始时间！',
    'Event' => '事件',
    'Event not found!' => '没找到事件',
    'ID' => 'ID',
    'Maybe attending users' => '可能参加的用户',
    'Participation Mode' => '参与模式',
    'Start Date' => '开始日期',
    'Title' => '标题',
    'You don\'t have permission to delete this event!' => '你无权删除事件！',
    'You don\'t have permission to edit this event!' => '你无权编辑事件！',
];
