<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> event' => '<strong>创建</strong> 事件',
    '<strong>Edit</strong> event' => '<strong>编辑</strong> 事件',
    '<strong>Note:</strong> This event will be created on your profile. To create a space event open the calendar on the desired space.' => '<strong>提示：</strong>此事件将在您的属性页面创建。若要创建一个版块日历事件，请在所需版块打开日历来创建。',
    'Delete' => '删除',
    'Description' => '描述',
    'End Date/Time' => '结束日期/时间',
    'Everybody can participate' => '所有人能参加',
    'No participants' => '没有参与者',
    'Title' => '标题',
];
