<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Attend' => '参加',
  'Created by:' => '创建人',
  'Decline' => '拒绝',
  'Edit this event' => '编辑事件',
  'I´m attending' => '我参加',
  'I´m maybe attending' => '我可能参加',
  'I´m not attending' => '我不参加',
  'Maybe' => '可能',
  'Public' => '公共',
);
