<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Adds an calendar for private or public events to your profile and mainmenu.' => 'Adiciona um calendário para eventos públicos ou privados em seu perfil no menu principal.',
  'Adds an event calendar to this space.' => 'Adicionar um evento para esse espaço.',
  'All Day' => 'Todos os dias',
  'Attending users' => 'Usuários confirmados',
  'Calendar' => 'Calendário',
  'Declining users' => 'Usuário que recusaram',
  'Description' => 'Descrição',
  'End Date' => 'Data final',
  'End Date and Time' => 'Date final e horário',
  'End time must be after start time!' => 'Horário final precisa ser depois do horário inicial.',
  'Event' => 'Evento',
  'Event not found!' => 'Evento não encontrando.',
  'ID' => 'Id',
  'Maybe attending users' => 'Usuário que talvez',
  'Participation Mode' => 'Mode de participação',
  'Recur' => 'Recorrente',
  'Recur End' => 'Final da recurrência',
  'Recur Interval' => 'Intervalo da recurrência',
  'Recur Type' => 'Tipo de recurrência',
  'Select participants' => 'Participantes selecionados',
  'Start Date' => 'Data inicial',
  'Start Date and Time' => 'Data inicial e horário',
  'Title' => 'Título',
  'You don\'t have permission to access this event!' => 'Você não tem permissão para acessar esse evento!',
  'You don\'t have permission to create events!' => 'Você não tem permissão para criar eventos!',
  'You don\'t have permission to delete this event!' => 'Você não tem permissão para remover eventos!',
  'You don\'t have permission to edit this event!' => 'Você não tem permissão para editar evento!',
);
