<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Event type color' => '',
    'Send update notification' => '',
    'canceled' => '',
    '<strong>Add</strong> profile calendar' => '<Strong>Voeg</ strong>een profielagenda toe',
    'Adds an calendar for private or public events to your profile and mainmenu.' => 'Voegt een agenda voor private of publieke evenementen toe aan uw profiel en hoofdmenu.',
    'Adds an event calendar to this space.' => 'Voegt een agenda toe aan deze ruimte.',
    'All Day' => 'Volledige dag',
    'Allow participation state \'decline\'' => 'Sta deelnamestatus \'afwijzen\' toe',
    'Allow participation state \'maybe\'' => 'Sta deelnamestatus \'misschien\' toe',
    'Attending' => 'Neem deel',
    'Attending users' => 'Deelnemers',
    'Calendar' => 'Agenda',
    'Close' => 'Sluit',
    'Declining users' => 'Afgewezen',
    'Description' => 'Beschrijving',
    'Edit' => 'Werk bij',
    'Enable' => 'Inschakelen',
    'End Date' => 'Einddatum',
    'End Time' => 'Eindtijd',
    'End time must be after start time!' => 'Einde moet na begin zijn!',
    'Event' => 'Gebeurtenis',
    'Event Type' => 'Gebeurtenistype',
    'Event not found!' => 'Gebeurtenis niet gevonden!',
    'ID' => 'ID',
    'In order to add events to your profile, you have to enable the calendar module first.' => 'Om gebeurtenissen toe te voegen aan uw profiel, moet u eerst de agendamodule inschakelen.',
    'Interested' => 'Belangstelling',
    'Invalid event type id selected.' => 'Ongeldige gebeurtenistype-id geselecteerd.',
    'Invited' => 'Uitnodiging',
    'Maximum number of participants' => 'Maximaal aantal deelnemers',
    'Maybe attending users' => 'Misschien',
    'Next' => 'Volgende',
    'Participation Mode' => 'Deelname',
    'Public' => 'Publiek',
    'Start Date' => 'Startdatum',
    'Start Time' => 'Starttijd',
    'Time Zone' => 'Tijdzone',
    'Title' => 'Titel',
    'You don\'t have permission to delete this event!' => 'Je hebt geen toestemming om dit evenement te verwijderen!',
];
