<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> Deletion' => '',
    'Create new type' => '',
    'Default event settings' => '',
    'Delete' => '',
    'Do you really want to delte this event type?' => '',
    'Event Type Configuration' => '',
    'Here you can configure default settings for new calendar events.' => '',
    'Here you can configure default settings for new calendar events. These settings can be overwritten on space/profile level.' => '',
    'Here you can manage your event types.' => '',
    'Name' => '',
    'Reset' => '',
    'There are currently no event types available.' => '',
    '<strong>Calendar</strong> module configuration' => '<strong>Kalender</ strong>moduleconfiguratie',
    'Adds an snippet with upcoming events to your users dashboard.' => 'Voegt een fragment toe met aankomende gebeurtenissen aan het gebruikersprikbord.',
    'Half a year' => 'Half jaar',
    'If activated, the calendar top menu item and dashboard snippet is only visible for users having the calendar module installed in their profile.' => 'Indien geactiveerd, is het bovenste menu-item en het dashboard-fragment in de kalender alleen zichtbaar voor gebruikers die de kalendermodule in hun profiel hebben geïnstalleerd.',
    'Interval of upcoming events' => 'Interval van komende gebeurtenissen',
    'Max event items' => 'Maximaal aantal gebeurtenissen',
    'One month' => 'Een maand',
    'One week' => 'Een week',
    'One year' => 'Een jaar',
    'Only show top menu item and snippet if the module is installed in the users profile' => 'Toon alleen het bovenste menu-item en het fragment als de module is geïnstalleerd in het gebruikersprofiel',
    'Show snippet' => 'Toon fragment',
    'Sort order' => 'Sorteervolgorde',
    'Upcoming events snippet' => 'Komende gebeurtenisfragment',
];
