<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'End Time' => '',
    'Start Time' => '',
    'End Date and Time' => 'Datum a čas konce',
    'Recur' => 'Opakování',
    'Recur End' => 'Konec opakování',
    'Recur Interval' => 'Interval opakování',
    'Recur Type' => 'Typ opakování',
    'Select participants' => 'Vybrat účastníky',
    'Start Date and Time' => 'Datum a čas začátku',
    'You don\'t have permission to access this event!' => 'Pro přístup k této události nemáte oprávnění!',
    'You don\'t have permission to create events!' => 'Nemáte oprávnění vytvořit událost!',
    'Adds an calendar for private or public events to your profile and mainmenu.' => 'Přidá kalendář s vašimi soukromými nebo veřejnými událostmi na váš profil a do hlavního menu.',
    'Adds an event calendar to this space.' => 'Přidá kalendář do tohoto prostoru.',
    'All Day' => 'Celý den',
    'Attending users' => 'Zúčastní se',
    'Calendar' => 'Kalendář',
    'Declining users' => 'Nezúčastní se ',
    'Description' => 'Popis',
    'End Date' => 'Datum konce',
    'End time must be after start time!' => 'Datum konce události musí následovat po začátku!',
    'Event' => 'Událost',
    'Event not found!' => 'Událost nebyla nenalezena!',
    'ID' => 'ID',
    'Maybe attending users' => 'Možná se zúčastní',
    'Participation Mode' => 'Kdo se může zúčasnit?',
    'Start Date' => 'Datum začátku',
    'Title' => 'Název',
    'You don\'t have permission to delete this event!' => 'Nemáte oprávnění smazat tuto událost!',
    'You don\'t have permission to edit this event!' => 'Nemáte oprávnění upravit tuto událost!',
];
