<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Add</strong> profile calendar' => '',
    '<strong>Choose</strong> target calendar' => '',
    'Allow participation state \'decline\'' => '',
    'Allow participation state \'maybe\'' => '',
    'Attending' => '',
    'Birthday' => '',
    'Cancel Event' => '',
    'Close' => '',
    'Download as ICS file' => '',
    'Edit' => '',
    'Enable' => '',
    'Event Type' => '',
    'Event type color' => '',
    'In order to add events to your profile, you have to enable the calendar module first.' => '',
    'Interested' => '',
    'Invalid event type id selected.' => '',
    'Maximum number of participants' => '',
    'Next' => '',
    'Profile Calendar' => '',
    'Public' => '',
    'Reopen Event' => '',
    'Send update notification' => '',
    'Time Zone' => '',
    'canceled' => '',
    '{displayName} Birthday' => '',
    'Adds a calendar for private or public events to your profile and main menu.' => 'Afegeix un calendari per esdeveniments públics o privats al teu perfil i al menú principal',
    'Adds an event calendar to this space.' => 'Afegeix un calendari a aquest espai.',
    'All Day' => 'Tot el dia',
    'Attending users' => 'Membres que hi assistiran',
    'Calendar' => 'Calendari',
    'Declining users' => 'Membres que no hi assistiran',
    'Description' => 'Descripció',
    'End Date' => 'Data final',
    'End Time' => 'Hora de finalització',
    'End time must be after start time!' => 'L\'hora final ha de ser després de l\'hora d\'inici!',
    'Event' => 'Esdeveniment',
    'Event not found!' => 'No s\'ha trobat l\'esdeveniment!',
    'ID' => 'ID',
    'Maybe attending users' => 'Membres que potser hi assistiran',
    'Participation Mode' => 'Mode de participaió',
    'Start Date' => 'Data d\'inici',
    'Start Time' => 'Hora d\'inici',
    'Title' => 'Títol',
    'You don\'t have permission to delete this event!' => 'No tens permisos per eliminar aquest esdeveniment!',
];
