<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Adds an calendar for private or public events to your profile and mainmenu.' => 'Fügt deinem Profil und Hauptmenü einen Kalender für private und öffentliche Termine hinzu.',
    'Adds an event calendar to this space.' => 'Fügt diesem Space einen Termin hinzu',
    'All Day' => 'Alle Tage',
    'Attending users' => 'Teilnehmende Benutzer',
    'Calendar' => 'Kalender',
    'Declining users' => 'Absagende Benutzer',
    'Description' => 'Beschreibung',
    'End Date' => 'Enddatum',
    'End Time' => 'Termin Ende',
    'End time must be after start time!' => 'Enddatum muss älter als Startdatum sein!',
    'Event' => 'Termin',
    'Event not found!' => 'Termin nicht gefunden!',
    'ID' => 'ID',
    'Maybe attending users' => 'Unsichere Benutzer',
    'Participation Mode' => 'Teilnahmemodus',
    'Start Date' => 'Startdatum',
    'Start Time' => 'Termin Anfang',
    'Title' => 'Titel',
    'You don\'t have permission to delete this event!' => 'Unzureichende Berechtigungen, diesen Termin zu löschen!',
    'You don\'t have permission to edit this event!' => 'Unzureichende Berechtigungen, diesen Termin zu ändern!',
];
