<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> Deletion' => '',
    'Create new type' => '',
    'Default event settings' => '',
    'Delete' => '',
    'Do you really want to delte this event type?' => '',
    'Event Type Configuration' => '',
    'Here you can configure default settings for new calendar events.' => '',
    'Here you can configure default settings for new calendar events. These settings can be overwritten on space/profile level.' => '',
    'Here you can manage your event types.' => '',
    'Name' => '',
    'Reset' => '',
    'There are currently no event types available.' => '',
    '<strong>Calendar</strong> module configuration' => '<strong>Kalender</strong> Modul-Konfiguration',
    'Adds an snippet with upcoming events to your users dashboard.' => 'Zeige einen Bereich mit den nächsten Terminen auf dem Dashboard.',
    'Half a year' => 'Ein halbes Jahr',
    'If activated, the calendar top menu item and dashboard snippet is only visible for users having the calendar module installed in their profile.' => 'Wenn diese Option aktiviert ist werden der Menüeintrag „Kalender“ und der Bereich „Nächste Termine“ nur dann angezeigt, wenn der Benutzer das Kalender-Modul in seinem Profil aktiviert hat.',
    'Interval of upcoming events' => 'Zeitspanne für Termine die als „demnächst“ betrachtet werden',
    'Max event items' => 'Maximale Anzahl angezeigter Termine',
    'One month' => 'Ein Monat',
    'One week' => 'Eine Woche',
    'One year' => 'Ein Jahr',
    'Only show top menu item and snippet if the module is installed in the users profile' => 'Zeige den Menüeintrag und „Nächste Termine“ nur bei aktiviertem Kalender-Modul im Benutzerprofil',
    'Show snippet' => 'Nächste Termine anzeigen',
    'Sort order' => 'Sortierung',
    'Upcoming events snippet' => 'Bereich „Nächste Termine“',
];
