<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<strong>Create</strong> event' => 'Termin <strong>erstellen</strong>',
  '<strong>Edit</strong> event' => 'Termin <strong>anpassen</strong>',
  '<strong>Note:</strong> This event will be created on your profile. To create a space event open the calendar on the desired space.' => '<strong>Beachte:</strong> Dieser Termin wird in deinem Profil erstellt. Um einen Termin in einem Space zu erstellen, öffne den Kalender im gewünschten Space.',
  'Close' => 'Schließen',
  'Delete' => 'Löschen',
  'Description' => 'Beschreibung',
  'End Date' => 'End-Datum',
  'End Date/Time' => 'End-Datum/Zeit',
  'Everybody can participate' => 'Jeder darf teilnehmen',
  'No participants' => 'Niemand darf teilnehmen',
  'Participants' => 'Teilnehmer',
  'Save' => 'Speichern',
  'Start Date' => 'Start-Datum',
  'Start Date/Time' => 'Start-Datum/Zeit',
  'Title' => 'Titel',
);
