<?php
<<<<<<< HEAD
<<<<<<< HEAD
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'I\'m attending' => '',
    '<strong>Filter</strong> events' => 'Termine <strong>filtern</strong>',
    '<strong>Select</strong> calendars' => 'Kalender <strong>auswählen</strong>',
    'Followed spaces' => 'Gefolgte Spaces',
    'Followed users' => 'Gefolgte Benutzer',
    'My events' => 'Meine Termine',
    'My profile' => 'Mein Profil',
    'My spaces' => 'Meine Spaces',
];
=======
=======
>>>>>>> parent of 118339f... Fixed: translation issue I'm attending
return array (
  '<strong>Filter</strong> events' => 'Termine <strong>filtern</strong>',
  '<strong>Select</strong> calendars' => 'Kalender <strong>auswählen</strong>',
  'Already responded' => 'Beantwortet',
  'Followed spaces' => 'Gefolgte Spaces',
  'Followed users' => 'Gefolgte Benutzer',
  'I´m attending' => 'Ich nehme teil',
  'My events' => 'Meine Termine',
  'My profile' => 'Mein Profil',
  'My spaces' => 'Meine Spaces',
  'Not responded yet' => 'Nicht beantwortet',
);
<<<<<<< HEAD
>>>>>>> parent of 118339f... Fixed: translation issue I'm attending
=======
>>>>>>> parent of 118339f... Fixed: translation issue I'm attending
