<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Add</strong> profile calendar' => '',
    '<strong>Choose</strong> target calendar' => '',
    'Allow participation state \'decline\'' => '',
    'Allow participation state \'maybe\'' => '',
    'Attending' => '',
    'Birthday' => '',
    'Cancel Event' => '',
    'Close' => '',
    'Download as ICS file' => '',
    'Edit' => '',
    'Enable' => '',
    'Event Type' => '',
    'Event type color' => '',
    'In order to add events to your profile, you have to enable the calendar module first.' => '',
    'Interested' => '',
    'Invalid event type id selected.' => '',
    'Maximum number of participants' => '',
    'Next' => '',
    'Profile Calendar' => '',
    'Public' => '',
    'Reopen Event' => '',
    'Send update notification' => '',
    'Time Zone' => '',
    'canceled' => '',
    '{displayName} Birthday' => '',
    'Adds a calendar for private or public events to your profile and main menu.' => 'یک تقویم برای رویدادهای خصوصی و یا عمومی به پروفایل شما و منوی اصلی اضافه‌می‌کند.',
    'Adds an event calendar to this space.' => 'به این انجمن یک تقویم رویداد اضافه‌می‌کند. ',
    'All Day' => 'تمام روز',
    'Attending users' => 'شرکت‌کنندگان',
    'Calendar' => 'تقویم',
    'Declining users' => 'کاربران غیرحاضر',
    'Description' => 'توضیحات',
    'End Date' => 'تاریخ پایان',
    'End Time' => 'پایان زمان',
    'End time must be after start time!' => 'تاریخ پایان باید پس از تاریخ آغاز باشد!',
    'Event' => 'رویداد',
    'Event not found!' => 'رویداد پیدا نشد!',
    'ID' => 'شناسه',
    'Maybe attending users' => 'کاربرانی که حضور آن‌ها قطعی نیست',
    'Participation Mode' => 'حالت مشارکت',
    'Start Date' => 'تاریخ شروع',
    'Start Time' => 'آغاز زمان',
    'Title' => 'عنوان',
    'You don\'t have permission to delete this event!' => 'شما اجازه‌ی پاک کردن این رویداد را ندارید!',
];
