<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> event' => '<strong>ساختن</strong> گروه',
    '<strong>Edit</strong> event' => '<strong>ویرایش</strong> گروه',
    '<strong>Note:</strong> This event will be created on your profile. To create a space event open the calendar on the desired space.' => '<strong>توجه:</strong> این رویداد در پروفایل شما ساخته خواهدشد. برای تولید رویداد انجمن، تقویم آن انجمن را باز کنید.',
    'Delete' => 'حذف',
    'Description' => 'توضیحات',
    'End Date/Time' => 'تاریخ/زمان اتمام',
    'Everybody can participate' => 'همه می‌توانند مشارکت کنند',
    'No participants' => 'مشارکت‌کننده‌ای وجود ندارد',
    'Title' => 'عنوان',
];
