<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Add</strong> profile calendar' => '',
    'Are you sure you want to delete this event?' => '',
    'Attending' => '',
    'Close' => '',
    'Edit' => '',
    'Enable' => '',
    'In order to add events to your profile, you have to enable the calendar module first.' => '',
    'Interested' => '',
    'Invited' => '',
    'Next' => '',
    'Public' => '',
    'Adds an calendar for private or public events to your profile and mainmenu.' => 'Legger til kalender for private eller offentlige hendelser til din profil og hovedmeny.',
    'Adds an event calendar to this space.' => 'Legger til en kalender i denne gruppen.',
    'All Day' => 'Hele dagen',
    'Attending users' => 'Brukere som deltar',
    'Calendar' => 'Kalender',
    'Declining users' => 'Brukere som ikke deltar',
    'Description' => 'Beskrivelse',
    'End Date' => 'Sluttdato',
    'End Time' => 'Slutt-tid',
    'End time must be after start time!' => 'Slutt må være etter starttid!',
    'Event' => 'Event',
    'Event not found!' => 'Event ikke funnet!',
    'ID' => 'ID',
    'Maybe attending users' => 'Brukere som kanskje deltar',
    'Participation Mode' => 'Deltagermodus',
    'Start Date' => 'Startdato',
    'Start Time' => 'Start-tid',
    'Title' => 'Tittel',
    'You don\'t have permission to delete this event!' => 'Du har ikke tilgang til å delta på denne eventen!',
    'You don\'t have permission to edit this event!' => 'Du har ikke tilgang til å redigere eventen!',
];
