<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(disabled)' => '',
    'Here you can manage calendar types provided by other modules.' => '',
    'Other Calendars Configuration' => '',
    '(global)' => '(global)',
    '<strong>Calendar</strong> module configuration' => 'Konfigurasjon <strong>Kalender</strong>modul',
    '<strong>Confirm</strong> Deletion' => '<strong>Bekreft</strong> sletting',
    'Adds an snippet with upcoming events to your users dashboard.' => 'Legger til en snippet med nærstående aktivitet til Oversikt',
    'Create new type' => 'Opprett ny',
    'Default event settings' => 'Standard aktivitetinnstillinger',
    'Delete' => 'Slett',
    'Do you really want to delte this event type?' => 'Bekreft sletting av aktivitetstype.',
    'Event Type Configuration' => 'Konfigurasjon aktivitetstyper',
    'Half a year' => 'Et halvt år',
    'Here you can configure default settings for new calendar events.' => 'Her kan du konfigurere standard innstillinger for kalender aktiviteter',
    'Here you can configure default settings for new calendar events. These settings can be overwritten on space/profile level.' => 'Her kan du konfigurere standard innstillinger for kalender aktiviteter. Innstillingene kan skrives over på gruppe- og profilnivå.',
    'Here you can manage your event types.' => 'Her kan du redigere dine aktivitetstyper',
    'If activated, the calendar top menu item and dashboard snippet is only visible for users having the calendar module installed in their profile.' => 'Hvis aktivert, vil Kalender kun vise i hovedmenyen og snippet under Oversikt kun være synlig for brukere som har kalendermodulen installert på sin profil.',
    'Interval of upcoming events' => 'Intervall for kommende aktiviteter ',
    'Max event items' => 'Maks antall aktiviteter',
    'Name' => 'Navn',
    'One month' => 'En måned',
    'One week' => 'En uke',
    'One year' => 'Ett år',
    'Only show top menu item and snippet if the module is installed in the users profile' => 'Vis kun øverste menypunkt og snippet hvis modulen er installert på brukerens profil',
    'Reset' => 'Tilbakestill',
    'Show snippet' => 'Vis snippet',
    'Sort order' => 'Sorteringsrekkefølge',
    'There are currently no event types available.' => 'Det er ingen aktivitetstyper tilgjengelig',
    'Upcoming events snippet' => 'Snippet for kommende aktiviteter',
];
