<?php
/**
 * @link https://www.humhub.org/
 * @copyright Copyright (c) 2019 HumHub GmbH & Co. KG
 * @license https://www.humhub.com/licences
 */

namespace humhub\modules\calendar\widgets;


use Yii;
use humhub\components\Widget;
use humhub\modules\content\components\ContentContainerActiveRecord;
use humhub\modules\content\helpers\ContentContainerHelper;
use humhub\modules\space\models\Space;
use humhub\widgets\Button;

class ConfigureButton extends Widget
{
    /**
     * @var ContentContainerActiveRecord
     */
    public $container;

    public function init()
    {
        $this->container = ContentContainerHelper::getCurrent();

        if(!$this->container) {
            $this->container = Yii::$app->user->getIdentity();
        }

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        if(Yii::$app->user->isGuest) {
            return '';
        }

        return Button::defaultType()->link($this->getConfigUrl())->right()->icon('fa-cog')->visible($this->canConfigure());
    }

    private function getConfigUrl()
    {
        return  $this->container->createUrl('/calendar/container-config');
    }

    public function canConfigure()
    {
        if($this->container instanceof Space) {
            return $this->container->isAdmin();
        } else {
            return $this->container->isCurrentUser();
        }
    }


}