<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(disabled)' => '',
    '(global)' => '',
    '<strong>Calendar</strong> module configuration' => '',
    '<strong>Confirm</strong> Deletion' => '',
    'Adds an snippet with upcoming events to your users dashboard.' => '',
    'Create new type' => '',
    'Default event settings' => '',
    'Delete' => '',
    'Do you really want to delte this event type?' => '',
    'Event Type Configuration' => '',
    'Half a year' => '',
    'Here you can configure default settings for new calendar events.' => '',
    'Here you can configure default settings for new calendar events. These settings can be overwritten on space/profile level.' => '',
    'Here you can manage calendar types provided by other modules.' => '',
    'Here you can manage your event types.' => '',
    'If activated, the calendar top menu item and dashboard snippet is only visible for users having the calendar module installed in their profile.' => '',
    'Interval of upcoming events' => '',
    'Max event items' => '',
    'Name' => '',
    'One month' => '',
    'One week' => '',
    'One year' => '',
    'Only show top menu item and snippet if the module is installed in the users profile' => '',
    'Other Calendars Configuration' => '',
    'Reset' => '',
    'Show snippet' => '',
    'Sort order' => '',
    'There are currently no event types available.' => '',
    'Upcoming events snippet' => '',
];
