<?php

/**
 * @link https://www.humhub.org/
 * @copyright Copyright (c) 2015 HumHub GmbH & Co. KG
 * @license https://www.humhub.com/licences
 */

namespace humhub\modules\calendar\assets;

use humhub\modules\ui\view\components\View;
use Yii;
use yii\web\AssetBundle;

class Assets extends AssetBundle
{
    public $publishOptions = [
        'forceCopy' => true
    ];
    
    public $sourcePath = '@calendar/resources';

    public $css = [
        'css/calendar.css',
        //'fullcalendar/fullcalendar.print.css', // print
    ];
    public $js = [
        'js/humhub.calendar.js'
    ];

    /**
     * @param View $view
     * @return AssetBundle
     */
    public static function register($view)
    {
        $view->registerJsConfig('calendar', [
            'text' => [
                'button.today' => Yii::t('CalendarModule.calendar', 'today'),
                'button.month' => Yii::t('CalendarModule.calendar', 'month'),
                'button.week' => Yii::t('CalendarModule.calendar', 'week'),
                'button.day' => Yii::t('CalendarModule.calendar', 'day'),
                'button.list' => Yii::t('CalendarModule.calendar', 'list'),
            ]
        ]);
        return parent::register($view); // TODO: Change the autogenerated stub
    }
}
