<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Add</strong> profile calendar' => '',
    '<strong>Choose</strong> target calendar' => '',
    'Adds a calendar for private or public events to your profile and main menu.' => '',
    'Adds an event calendar to this space.' => '',
    'All Day' => '',
    'Allow participation state \'decline\'' => '',
    'Allow participation state \'maybe\'' => '',
    'Attending' => '',
    'Attending users' => '',
    'Birthday' => '',
    'Calendar' => '',
    'Cancel Event' => '',
    'Close' => '',
    'Declining users' => '',
    'Description' => '',
    'Download as ICS file' => '',
    'Edit' => '',
    'Enable' => '',
    'End Date' => '',
    'End Time' => '',
    'End time must be after start time!' => '',
    'Event' => '',
    'Event Type' => '',
    'Event not found!' => '',
    'Event type color' => '',
    'ID' => '',
    'In order to add events to your profile, you have to enable the calendar module first.' => '',
    'Interested' => '',
    'Invalid event type id selected.' => '',
    'Maximum number of participants' => '',
    'Maybe attending users' => '',
    'Next' => '',
    'Participation Mode' => '',
    'Profile Calendar' => '',
    'Public' => '',
    'Reopen Event' => '',
    'Send update notification' => '',
    'Start Date' => '',
    'Start Time' => '',
    'Time Zone' => '',
    'Title' => '',
    'You don\'t have permission to delete this event!' => '',
    'canceled' => '',
    '{displayName} Birthday' => '',
];
