<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Add</strong> profile calendar' => '',
    'Adds an calendar for private or public events to your profile and mainmenu.' => '',
    'Adds an event calendar to this space.' => '',
    'All Day' => '',
    'Are you sure you want to delete this event?' => '',
    'Attending' => '',
    'Attending users' => '',
    'Calendar' => '',
    'Close' => '',
    'Declining users' => '',
    'Description' => '',
    'Edit' => '',
    'Enable' => '',
    'End Date' => '',
    'End Time' => '',
    'End time must be after start time!' => '',
    'Event' => '',
    'Event not found!' => '',
    'ID' => '',
    'In order to add events to your profile, you have to enable the calendar module first.' => '',
    'Interested' => '',
    'Invited' => '',
    'Maybe attending users' => '',
    'Next' => '',
    'Participation Mode' => '',
    'Public' => '',
    'Start Date' => '',
    'Start Time' => '',
    'You don\'t have permission to delete this event!' => '',
    'You don\'t have permission to edit this event!' => '',
    'Title' => '標題',
];
