<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Choose</strong> target calendar' => '',
    'Birthday' => '',
    'Cancel Event' => '',
    'Download as ICS file' => '',
    'Profile Calendar' => '',
    'Reopen Event' => '',
    '{displayName} Birthday' => '',
    '<strong>Add</strong> profile calendar' => '<strong>Thêm</strong> lịch riêng',
    'Adds a calendar for private or public events to your profile and main menu.' => 'Thêm lịch cho sự kiện riêng tư hoặc công cộng vào Trang hồ sơ và Menu chính của bạn.',
    'Adds an event calendar to this space.' => 'Thêm lịch sự kiện vào Phòng làm việc này',
    'All Day' => 'Cả ngày',
    'Allow participation state \'decline\'' => 'Cho phép người tham gia tuyên bố "từ chối"',
    'Allow participation state \'maybe\'' => 'Cho phép người tham gia tuyên bố "có thể"',
    'Attending' => 'Sẽ tham gia',
    'Attending users' => 'Các thành viên tham gia',
    'Calendar' => 'Lịch ',
    'Close' => 'Đóng',
    'Declining users' => 'Từ chối thành viên',
    'Description' => 'Mô tả',
    'Edit' => 'Chỉnh sửa',
    'Enable' => 'Kích hoạt',
    'End Date' => 'Ngày kết thúc',
    'End Time' => 'Giờ kết thúc',
    'End time must be after start time!' => 'Ngày kết thúc phải sau ngày bắt đầu!',
    'Event' => 'Sự kiện',
    'Event Type' => 'Loại sự kiện',
    'Event not found!' => 'Không tìm thấy sự kiện!',
    'Event type color' => 'Mâu loại sự kiện',
    'ID' => 'ID',
    'In order to add events to your profile, you have to enable the calendar module first.' => 'Để thêm sự kiện vào trang hồ sơ của bạn, bạn phải kích hoạt module Lịch trước.',
    'Interested' => 'Hứng thú.',
    'Invalid event type id selected.' => 'Sai ID loại sự kiện',
    'Maximum number of participants' => 'Số người tham dự tối đa',
    'Maybe attending users' => 'Số người "có thể" tham dự',
    'Next' => 'Tiếp theo',
    'Participation Mode' => 'Chế độ tham gia',
    'Public' => 'Công cộng',
    'Send update notification' => 'Gửi thông báo cập nhật',
    'Start Date' => 'Ngày bắt đầu',
    'Start Time' => 'Thời gian bắt đầu',
    'Time Zone' => 'Múi giờ',
    'Title' => 'Tiêu đề',
    'You don\'t have permission to delete this event!' => 'Bạn không có quyền xóa sự kiện này!',
    'canceled' => 'đã hủy',
];
