<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Add</strong> profile calendar' => '',
    'Are you sure you want to delete this event?' => '',
    'Attending' => '',
    'Close' => '',
    'Edit' => '',
    'Enable' => '',
    'In order to add events to your profile, you have to enable the calendar module first.' => '',
    'Interested' => '',
    'Invited' => '',
    'Next' => '',
    'Public' => '',
    'Adds an calendar for private or public events to your profile and mainmenu.' => 'Dodaje kalendarz dla wydarzeń prywatnych lub publicznych do twojego profilu i głównego menu.',
    'Adds an event calendar to this space.' => 'Dodaje kalendarz wydarzeń do tej strefy.',
    'All Day' => 'Wszystkie dni',
    'Attending users' => 'Użytkownicy biorący udział',
    'Calendar' => 'Kalendarz ',
    'Declining users' => 'Użytkownicy nie biorący udziału',
    'Description' => 'Opis',
    'End Date' => 'Data zakończenia',
    'End Time' => 'Koniec',
    'End time must be after start time!' => 'Data zakończenia musi być po dacie początku! ',
    'Event' => 'Wydarzenie',
    'Event not found!' => 'Nie znaleziono wydarzenia! ',
    'ID' => 'Identyfikator',
    'Maybe attending users' => 'Możliwi użytkownicy biorący udział',
    'Participation Mode' => 'Tryb uczestnictwa',
    'Start Date' => 'Data początku',
    'Start Time' => 'Początek',
    'Title' => 'Tytuł',
    'You don\'t have permission to delete this event!' => 'Nie masz uprawnień aby usunąć to wydarzenie!',
    'You don\'t have permission to edit this event!' => 'Nie masz uprawnień aby edytować to wydarzenie! ',
];
