<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'End Time' => '',
    'Start Time' => '',
    'End Date and Time' => 'Data i czas zakończenia',
    'Recur' => 'Powtarza się',
    'Recur End' => 'Zakończenie powtarzania się ',
    'Recur Interval' => 'Przedział powtarzania się ',
    'Recur Type' => 'Typ powtarzania się ',
    'Select participants' => 'Wybierz uczestników',
    'Start Date and Time' => 'Data i czas początku',
    'You don\'t have permission to access this event!' => 'Nie masz uprawnień aby mieć dostęp do tego wydarzenia! ',
    'You don\'t have permission to create events!' => 'Nie masz uprawnień aby tworzyć wydarzenia! ',
    'Adds an calendar for private or public events to your profile and mainmenu.' => 'Dodaje kalendarz dla wydarzeń prywatnych lub publicznych do twojego profilu i głównego menu.',
    'Adds an event calendar to this space.' => 'Dodaje kalendarz wydarzeń do tej strefy.',
    'All Day' => 'Wszystkie dni',
    'Attending users' => 'Użytkownicy biorący udział',
    'Calendar' => 'Kalendarz ',
    'Declining users' => 'Użytkownicy nie biorący udziału',
    'Description' => 'Opis',
    'End Date' => 'Data zakończenia',
    'End time must be after start time!' => 'Data zakończenia musi być po dacie początku! ',
    'Event' => 'Wydarzenie',
    'Event not found!' => 'Nie znaleziono wydarzenia! ',
    'ID' => 'Identyfikator',
    'Maybe attending users' => 'Możliwi użytkownicy biorący udział',
    'Participation Mode' => 'Tryb uczestnictwa',
    'Start Date' => 'Data początku',
    'Title' => 'Tytuł',
    'You don\'t have permission to delete this event!' => 'Nie masz uprawnień aby usunąć to wydarzenie!',
    'You don\'t have permission to edit this event!' => 'Nie masz uprawnień aby edytować to wydarzenie! ',
];
