<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Add</strong> profile calendar' => '',
    '<strong>Choose</strong> target calendar' => '',
    'Adds a calendar for private or public events to your profile and main menu.' => '',
    'Adds an event calendar to this space.' => '',
    'Birthday' => '',
    'Cancel Event' => '',
    'Download as ICS file' => '',
    'In order to add events to your profile, you have to enable the calendar module first.' => '',
    'Profile Calendar' => '',
    'Reopen Event' => '',
    '{displayName} Birthday' => '',
    'All Day' => 'Teljes nap',
    'Allow participation state \'decline\'' => '\'Nem vesz részt\' státusz engedélyezése',
    'Allow participation state \'maybe\'' => '\'Talán\' státusz engedélyezése',
    'Attending' => 'Részt vevő',
    'Attending users' => 'Részt vevő felhasználók',
    'Calendar' => 'Naptár',
    'Close' => 'Bezár',
    'Declining users' => 'Nem résztvevő felhasználók',
    'Description' => 'Leírás',
    'Edit' => 'Szerkeszt',
    'Enable' => 'Engedélyez',
    'End Date' => 'Záró dátum',
    'End Time' => 'Záró idő',
    'End time must be after start time!' => 'Záró időnek a kezdő idő után kell lennie!',
    'Event' => 'Esemény',
    'Event Type' => 'Esemény típusa',
    'Event not found!' => 'Esemény nem létezik',
    'Event type color' => 'Esemény típus színe',
    'ID' => 'ID',
    'Interested' => 'Érdeklődik',
    'Invalid event type id selected.' => 'Érvénytelen esemény id lett kiválasztva.',
    'Maximum number of participants' => 'Résztvevők maximális száma',
    'Maybe attending users' => 'Talán résztvevő felhasználók',
    'Next' => 'Következő',
    'Participation Mode' => 'Részvétel módja',
    'Public' => 'Nyilvános',
    'Send update notification' => 'Értesítés küldése',
    'Start Date' => 'Kezdő dátum',
    'Start Time' => 'Kezdet időpontja',
    'Time Zone' => 'Időzóna',
    'Title' => 'Cím',
    'You don\'t have permission to delete this event!' => 'Nincs jogosultságod törölni az eseményt!',
    'canceled' => 'törölve',
];
