<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Add</strong> profile calendar' => '',
    'Allow participation state \'decline\'' => '',
    'Allow participation state \'maybe\'' => '',
    'Attending' => '',
    'Close' => '',
    'Edit' => '',
    'Enable' => '',
    'Event Type' => '',
    'Event type color' => '',
    'In order to add events to your profile, you have to enable the calendar module first.' => '',
    'Interested' => '',
    'Invalid event type id selected.' => '',
    'Invited' => '',
    'Maximum number of participants' => '',
    'Next' => '',
    'Public' => '',
    'Send update notification' => '',
    'Time Zone' => '',
    'canceled' => '',
    'Adds an calendar for private or public events to your profile and mainmenu.' => 'Se adaugă un calendar pentru evenimente private sau publice pe profilul tău și pe meniul principal.',
    'Adds an event calendar to this space.' => 'Se adaugă un calendar de evenimente pe acest spațiu.',
    'All Day' => 'Toată Ziua',
    'Attending users' => 'Utilizatori participanți',
    'Calendar' => 'Calendar',
    'Declining users' => 'Utilizatori neparticipanți',
    'Description' => 'Descriere',
    'End Date' => 'Data Scadentă',
    'End Time' => 'Sfarsit',
    'End time must be after start time!' => 'Timpul scadent trebuie să fie după timpul de început!',
    'Event' => 'Eveniment',
    'Event not found!' => 'Evenimentul nu a fost găsit!',
    'ID' => 'ID',
    'Maybe attending users' => 'Utilizatori care probabil vor participa',
    'Participation Mode' => 'Mod de Participare',
    'Start Date' => 'Data Începerii',
    'Start Time' => 'Inceput',
    'Title' => 'Titlul',
    'You don\'t have permission to delete this event!' => 'Nu ai permisiunea să ștergi acest eveniment!',
];
