<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> event' => '<strong>Crează</strong> eveniment',
    '<strong>Edit</strong> event' => '<strong>Editează</strong> eveniment',
    '<strong>Note:</strong> This event will be created on your profile. To create a space event open the calendar on the desired space.' => '<strong>Notă:</strong> Acest eveniment va fi creat pe profilul tău. Pentru a crea un eveniment de spațiu deschide calendarul pe spațiul dorit.',
    'Delete' => 'Șterge',
    'Description' => 'Descriere',
    'End Date/Time' => 'Data/Timpul Scadent',
    'Everybody can participate' => 'Oricine poate participa',
    'No participants' => 'Fără participanți',
    'Title' => 'Titlul',
];
