<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Add</strong> profile calendar' => '',
    '<strong>Choose</strong> target calendar' => '',
    'Allow participation state \'decline\'' => '',
    'Allow participation state \'maybe\'' => '',
    'Attending' => '',
    'Birthday' => '',
    'Cancel Event' => '',
    'Close' => '',
    'Download as ICS file' => '',
    'Edit' => '',
    'Enable' => '',
    'Event Type' => '',
    'Event type color' => '',
    'In order to add events to your profile, you have to enable the calendar module first.' => '',
    'Interested' => '',
    'Invalid event type id selected.' => '',
    'Maximum number of participants' => '',
    'Next' => '',
    'Profile Calendar' => '',
    'Public' => '',
    'Reopen Event' => '',
    'Send update notification' => '',
    'Time Zone' => '',
    'canceled' => '',
    '{displayName} Birthday' => '',
    'Adds a calendar for private or public events to your profile and main menu.' => 'Tilføjer en kalender for private eller offentlige events til din profil og mainmenu.',
    'Adds an event calendar to this space.' => 'Tilføjer en event kalender til denne side',
    'All Day' => 'Hele dagen',
    'Attending users' => 'Deltagende brugere',
    'Calendar' => 'Kalender',
    'Declining users' => 'Ikke-deltagende brugere',
    'Description' => 'Beskrivelse',
    'End Date' => 'Slut Dato',
    'End Time' => 'Slut tidspunkt',
    'End time must be after start time!' => 'Slut tidspunkt skal være efter start tidspunkt!',
    'Event' => 'Event',
    'Event not found!' => 'Event ikke fundet!',
    'ID' => 'ID',
    'Maybe attending users' => 'Måske deltagende brugere',
    'Participation Mode' => 'Deltagelses tilstand',
    'Start Date' => 'Start Dato',
    'Start Time' => 'Start Tidspunkt',
    'Title' => 'Titel',
    'You don\'t have permission to delete this event!' => 'Du har ikke adgang til at slette dette event!',
];
