<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> event' => '<strong>Opret</strong> event',
    '<strong>Edit</strong> event' => '<strong>Rediger</strong> event',
    '<strong>Note:</strong> This event will be created on your profile. To create a space event open the calendar on the desired space.' => '<strong>Bemærk:</strong> Dette event vil blive oprettet på din profil. For at oprette en side event skal du åbne kalenderen på den ønskede side.',
    'Delete' => 'Slet',
    'Description' => 'Beskrivelse',
    'End Date/Time' => 'Slut Dato/Tid',
    'Everybody can participate' => 'Alle kan deltage',
    'No participants' => 'Ingen deltagere',
    'Title' => 'Titel',
];
