<?php


namespace humhub\modules\calendar\models\forms;


use humhub\modules\calendar\models\CalendarReminder;
use humhub\modules\content\components\ContentContainerActiveRecord;
use Yii;
use yii\base\Model;

class ReminderSettings extends Model
{
    /**
     * @var ContentContainerActiveRecord
     */
    public $container;

    /**
     * @var CalendarReminder[]
     */
    public $reminder;

    public function init()
    {
        parent::init();
        $this->loadReminder();

    }

    public function loadReminder()
    {
        $this->reminder = CalendarReminder::getDefaults($this->container, true);
        $this->reminder[] = new CalendarReminder();
    }

    /**
     * @return array
     */
    public static function getUnitSelection()
    {
        return [
            CalendarReminder::UNIT_HOUR => Yii::t('CalendarModule.reminder', 'Hour'),
            CalendarReminder::UNIT_DAY => Yii::t('CalendarModule.reminder', 'Day'),
            CalendarReminder::UNIT_WEEK => Yii::t('CalendarModule.reminder', 'Week'),
        ];
    }

    public function load($data, $formName = null)
    {
        if(isset($data[CalendarReminder::instance()->formName()])) {
            CalendarReminder::clearDefaults($this->container);
            foreach ($data[CalendarReminder::instance()->formName()] as $reminderData) {
                $remidner = new CalendarReminder(['active' => 1]);
                $remidner->load($reminderData, '');
                $remidner->save();
            }

            // Update
            $this->loadReminder();
        }

        return parent::load($data, $formName); // TODO: Change the autogenerated stub
    }

    public function createFromPost($values = [])
    {
        /*static::loadMultiple()
        $count = count(Yii::$app->request->post('Setting', []));
        $settings = [new Setting()];
        for($i = 1; $i < $count; $i++) {
            $settings[] = new Setting();
        }*/
    }

}